name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: npm install
      
    - name: Test
      run: npm run test:unit
      
    - name: Build
      run: npm run build:prod
      
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /var/www
          rm -rf html.bak
          mv html html.bak
          mkdir html 